version: '3.9'

services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - my_network

networks:
  my_network:

volumes:
  db_data:
